### ISSUE TITLE
AWS OTA (Over The Air) Update

### ISSUE THREAD

**Issue by afloresalmeida** [ExploreEmbedded/Hornbill-Examples#26]
I'd like to know if you guys are planning to put in **your Arduino AWS IoT Library** (by the way, it is awesome), the functionality for **OTA (Over The Air) Update**, to use it using the Arduino IDE and AWS IoT OTA. Thanks in advance for any help in this.

**Comment by SaheblalBagwan** [comment]
https://github.com/BuildStormTechnologies
Kindly check the above link for our latest libraries, with additional features such as:
- Device provisioning.
- Shadow updates.
- Jobs management.
- Over-the-Air (OTA) updates.
- Mobile app for aws 

Additionally, you can explore libraries tailored for various platforms such as Azure, Thingboard, and Kaa IoT,  supporting both WiFi and cellular-based applications.
